import './globals.css'
import type { Metadata } from 'next'
import localFont from 'next/font/local'
import { Providers } from '@app/redux/provider'

const memesiqueFont = localFont({
  src: '../assets/fonts/Memesique-Regular.ttf',
  variable: '--font-memesique'
})

const gretarosFont = localFont({
  src: '../assets/fonts/Gretaros-Regular.ttf',
  variable: '--font-gretaros'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${memesiqueFont.variable} ${gretarosFont.variable}`}><Providers>{children}</Providers></body>
    </html>
  )
}
